### ISSUE TITLE
Crashes on file containing *only* markdown header

### ISSUE THREAD

**Issue by mikowitz** [mikowitz/xettelkasten_server#33]
The following content saved to a watched file, will cause the GenServer to crash

```markdown
title: hello
tags:
- tag
```

with this error

```elixir
10:17:07.071 [error] GenServer #PID<0.657.0> terminating
** (BadMapError) expected a map, got: [%{"tags" => nil}, "satie", "score"]
    (stdlib 3.17) :maps.merge(%{"tags" => [], "title" => nil}, [%{"tags" => nil}, "satie", "score"])
    (xettelkasten_server 0.1.0) lib/xettelkasten_server/note_file_reader.ex:28: XettelkastenServer.NoteFileReader.split_yaml_and_markdown/1
    (xettelkasten_server 0.1.0) lib/xettelkasten_server/note_file_reader.ex:11: XettelkastenServer.NoteFileReader.read/1
    (xettelkasten_server 0.1.0) lib/xettelkasten_server/note.ex:13: XettelkastenServer.Note.from_path/1
```

The matching in the file reader function does not have a case for when only the YAML header is present

**Comment by mikowitz** [comment]
Not a real error, PEBCAK
